dist: xenial
language: python
python: "3.7"
install:
  python setup.py develop
script:
  - python freeze.py
  - mkdir build
  - cp -R index.html static build
deploy:
  provider: pages
  local-dir: build
  target-branch: gh-pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true